strlen_test: strlen_test.c
	gcc strlen_test.c -o strlen_test






# output: strlen_test.o ft_strlen.o
# 	gcc strlen_test.o ft_strlen.o -o output

# strlen_test.o: strlen_test.c
# 	gcc -c strlen_test.c

# ft_strlen.o: ft_strlen.c libft.h
# 	gcc -c ft_strlen.c

# clean: 
# 	rm *.o  output